### ISSUE TITLE
看你也在用bitcron了，有没有打算移植到bitcron呢

### ISSUE THREAD

**Issue by skyue** [Sunnyyoung/Farbox-NexT#3]
用hexo的时候，就非常喜欢这个主题，目前在用ghost，也有移植版，正在考虑换到bitcron，唯一让我遗憾的就是这个主题，可惜自己不会代码，不知道作者有没有计划搞一个出来？

**Comment by sunnyyoung** [comment]
@skyue 前段时间就做了移植了，还在完善中。囧rz

**Comment by sunnyyoung** [comment]
@skyue 已经完成，参考 https://bitcron.com/system/themes 中的 https://blog-next--theme.bitcron.com
